import Hero from "./header/Hero";
import Footer from "./Footer";
import Billing from "./Billing";
import Business from "./Business";
import Button from "./components/Button";
import CardDeal from "./CardDeal";
import Clients from "./Clients";
import CTA from "./CTA";
import FeedbackCard from "./FeedbackCard";
import GetStarted from './GetStarted';
import Navbar from "./Navbar";
import Stats from "./Stats";
import Testimonials from './Testimonials'
export { Hero,Footer,Billing,Business,Button,CardDeal,Clients,CTA,FeedbackCard,GetStarted,Navbar,Stats,Testimonials };